# DataSource Configuration
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# Disable Flyway
  flyway:
    enabled: false

axon:
  serializer:
    ## xstream is not compatible anymore with jdk17+
    general: jackson
  axonserver:
    enabled: false
  eventhandling:
    processors:
      default:
        mode: tracking
  eventstore:
    jdbc:
      schema: axon

application:
  debug:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  simple:
    metrics:
      export:
        enabled: true
